// Matches the style already in the codebase: no semicolons, single quotes,
// trailing commas. Written now so it is ready the moment the dependency can be
// installed — see the note in package.json's `lint` script.
import antfu from '@antfu/eslint-config'

export default antfu({
  vue: true,
  typescript: true,

  // Generated by unplugin-*; rewritten on every build, so linting them only
  // produces noise nobody can act on.
  ignores: [
    'src/types/components.d.ts',
    'src/types/auto-imports.d.ts',
    'dist',
  ],

  rules: {
    // The project uses `const` arrow functions in <script setup> throughout.
    'antfu/top-level-function': 'off',
    // Vue SFC blocks are already ordered consistently by hand.
    'vue/block-order': 'off',
  },
})
